robot_cfg:
  kinematics:
    usd_path: robot/iiwa14/usds/iiwa_left_robotiq.usd
    usd_robot_root: "/robot/iiwa14"
      #usd_flip_joints: {}
      #usd_flip_joint_limits: []

    urdf_path: robot/iiwa14/iiwa_robotiq.urdf
    asset_root_path: robot/iiwa14
    
    base_link: "world"
    ee_link: "robotiq_base_link"
      #link_names: null
      #lock_joints: null
      #extra_links: null

    collision_link_names: 
      - lbr_link_0
      - lbr_link_1
      - lbr_link_2
      - lbr_link_3
      - lbr_link_4
      - lbr_link_5
      - lbr_link_6
      - lbr_link_7
      - robotiq_to_lbr_mount
      - robotiq_link
    collision_spheres: spheres/iiwa_robotiq.yml 
    collision_sphere_buffer: 0.005 
      #extra_collision_spheres: {}
    self_collision_ignore: 
      {
        world: [lbr_link_0, lbr_link_1],
        lbr_link_0: [lbr_link_1, lbr_link_2],
        lbr_link_1: [lbr_link_2, lbr_link_3],
        lbr_link_2: [lbr_link_3, lbr_link_4],
        lbr_link_3: [lbr_link_4, lbr_link_5, lbr_link_6, lbr_link_7, robotiq_link],
        lbr_link_4: [lbr_link_5, lbr_link_6, lbr_link_7, robotiq_to_lbr_mount, robotiq_link],
        lbr_link_5: [lbr_link_6, lbr_link_7, robotiq_to_lbr_mount, robotiq_link],
        lbr_link_6: [lbr_link_7, robotiq_to_lbr_mount, robotiq_link],
        lbr_link_7: [robotiq_to_lbr_mount, robotiq_link],
        robotiq_to_lbr_mount: [robotiq_link],
      } 
    self_collision_buffer: 
      lbr_link_0: 0.0
      lbr_link_1: 0.0
      lbr_link_2: 0.0
      lbr_link_3: 0.0
      lbr_link_4: 0.0
      lbr_link_5: 0.0
      lbr_link_6: 0.0
      lbr_link_7: 0.0
      robotiq_to_lbr_mount: 0.0
      robotiq_link: 0.0
      
        #use_global_cumul: True
    mesh_link_names: 
      - lbr_link_0
      - lbr_link_1
      - lbr_link_2
      - lbr_link_3
      - lbr_link_4
      - lbr_link_5
      - lbr_link_6
      - lbr_link_7
      - robotiq_to_lbr_mount
      - robotiq_link
        #external_asset_path: null 

    cspace:
      joint_names: 
        [
          "lbr_A1", 
          "lbr_A2", 
          "lbr_A3", 
          "lbr_A4", 
          'lbr_A5', 
          "lbr_A6", 
          "lbr_A7", 
        ] 
      retract_config: 
        - 0.0
        - -0.78
        - 0.0
        - -1.4
        - 0.0
        - 0.6
        - 0.0
      null_space_weight: 
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
      cspace_distance_weight: 
        - 1.0
        - 0.9
        - 0.8
        - 0.8
        - 0.7
        - 0.6
        - 0.5
      max_jerk: 100.0
      max_acceleration: 1.
