collision_spheres:
    lbr_link_0:
        - "center": [0.0, 0.0, 0.12]
          "radius": 0.11
    lbr_link_1:
        - "center": [0.0, -0.04, 0.2]
          "radius": 0.08
    lbr_link_2:
        - "center": [0.0, 0.07, 0.0]
          "radius": 0.075
    lbr_link_3:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.08
        - "center": [0.0, 0.045, 0.18]
          "radius": 0.07
    lbr_link_4:
        - "center": [0.0, -0.06, 0.01]
          "radius": 0.07
    lbr_link_5:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.07
    lbr_link_6:
        - "center": [0.0, 0.03, 0.0]
          "radius": 0.055
        - "center": [0.0, 0.08, -0.02]
          "radius": 0.06
    lbr_link_7:
        - "center": [0.0, 0.0, 0.01]
          "radius": 0.04
    lbr_link_ee: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.005
    reflex2_extra_shell: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_shell_link: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_pad_link: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_palm_link: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.005
    reflex_swivel_link_1: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_proximal_link_1: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_proximal_pad_link_1: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_flex_link_1: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_distal_link_1: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_distal_pad_link_1: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_swivel_link_2: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_proximal_link_2: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_proximal_pad_link_2: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_flex_link_2: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_distal_link_2: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_distal_pad_link_2: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_proximal_link_3: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_proximal_pad_link_3: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_flex_link_3: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_distal_link_3: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    reflex_distal_pad_link_3: 
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.01
    
